Modidfied code so as .env file is sourced correctly
fredrikhgrelland/vagrant-hashistack pull request #311
Opened 2020-09-10 11:14 UTC by Neha-Sinha2305

Corrected the file path for .env file in install.yml.

2020-09-10 12:32 UTC, zhenik commented on CHANGELOG.md
> +- source .env file
```suggestion
- Source .env file #308
```

2020-09-11 06:15 UTC, zhenik requested changes

2020-09-11 06:15 UTC, zhenik commented on CHANGELOG.md
> +- Source .env file
```suggestion
- Escape single quotes in CHANGELOG.md file #296 
- Source .env file #308 
```

2020-09-11 06:38 UTC, zhenik approved these changes

2020-09-11 06:42 UTC, pdmthorsrud approved these changes
LGTM

2020-09-11 07:24 UTC, merged